name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    name: Publish on GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Next build
        run: yarn next build
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}

      - name: Next export
        run: yarn next export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: hashfunc.io
          force_orphan: true
