name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    name: Publish on GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set yarn berry
        run: yarn set version berry

      - name: Install dependencies
        run: yarn install

      - name: Next build
        run: yarn next build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: hashfunc.io
          force_orphan: true
